request:
  name: Send request to model server
  description: Sends prompt or features to the TCP model server
  fields:
    model_key:
      required: true
      example: "llama2"
      selector:
        text:
    features:
      required: false
      example: [1.0, 2.0]
      selector:
        object:
    prompt:
      required: false
      example: "What is the capital of France?"
      selector:
        text:
